### ISSUE TITLE
Can't start Rails server with this gem installed

### ISSUE THREAD

**Issue by davidlink** [neopoly/bottle_rocket#10]
After installing this gem, I get the following error when running `rails server`:

```bin/rails:6: warning: already initialized constant APP_PATH```

When I remove this gem, my server starts up as expected. Any ideas?

**Update:** I thought maybe it was a problem with bin, so I `rake rails:update:bin`... now I'm getting:

````require': cannot load such file -- time_spanner (LoadError)
	from /Users/david/.rvm/gems/ruby-2.1.2@counteroffer/gems/bottle_rocket-0.0.1/lib/bottle_rocket.rb:1:in `<top (required)>'```

**Comment by shlub** [comment]
Sorry, this project is far from being finished and currently ob hold.
