### ISSUE TITLE
Callback when reaches cero?

### ISSUE THREAD

**Issue by ssoulless** [neopoly/bottle_rocket#9]
I have an "oferts" model in my app, you can set the time it's gonna be available and there is where the countdown plays.

the bottle_rocket is working like a charm, but Im facing a problem, how do I get the event when the countdown reaches cero?

I mean, my "oferts" model has a boolean attribute "active", I want when the countdown ends change the attribute "active" to false

I think the right way is using a callback, or there is another way?

**Comment by shlub** [comment]
bottle_rocket is not made to be used as a delayed job for models. It should be used to display a countdown on a html page. There is no callback function on the server side.

You could write a simple ruby script that checks the time in an endless loop and updates the model if that time is reached.

**Comment by ssoulless** [comment]
Thanks, when is it gonna be available? I tried to install it but it still shows an error when you try to start the server, are you planning to make a stable release soon?

**Comment by shlub** [comment]
Unfortunately this is on hold right now, and its not ready to be released.
